apiVersion: v1
kind: Pod
metadata:
  name: downward-api-demo
spec:
  containers:
    - name: flask-container
      image: shunny822/downward-api:v2
      ports:
        - containerPort: 5000
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace